version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-resource-tracker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g53xgeo0bjd"
s3_prefix = "aws-resource-tracker"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
